services:

  server:
    build: 
      context: .  
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true  # Keeps the container running for debugging
    networks:
      - prisma-network
networks:
  prisma-network:
    name: prisma-network